
export enum ArmorType {
    HELMET = "HELMET",
    CHEST = "CHEST",
    GAUNTLETS = "GAUNTLETS",
    LEGS = "LEGS",
}

export enum ModType {
    NONE = "NONE",
    MOBILITY_5 = "MOBILITY_5",
    RESILIENCE_5 = "RESILIENCE_5",
    RECOVERY_5 = "RECOVERY_5",
    DISCIPLINE_5 = "DISCIPLINE_5",
    INTELLECT_5 = "INTELLECT_5",
    STRENGTH_5 = "STRENGTH_5",
    MOBILITY_10 = "MOBILITY_10",
    RESILIENCE_10 = "RESILIENCE_10",
    RECOVERY_10 = "RECOVERY_10",
    DISCIPLINE_10 = "DISCIPLINE_10",
    INTELLECT_10 = "INTELLECT_10",
    STRENGTH_10 = "STRENGTH_10"
}
  